SelfFolio/SelF/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

#from django.contrib.auth import views as auth_views
from SelF import views
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jsi18n',JavaScriptCatalog.as_view(),name="js-catlog"),
    url('^$', views.welcome, name='welcome'),
    url('', include("django.contrib.auth.urls")),
    path("signup/", views.signup, name="signup"),
    path('login_page/', views.login_func, name='login_page'),
    path('logout_page/', views.logout_func, name="logout_page"),
    path('home/', views.home, name='home'),
    path('profile/',views.profile, name='profile'),
    url('editProfile',views.editProfile, name='editProfile'),
    path('attendance/', views.attendance, name='attendance'),
    url('addSub/', views.addSub, name='addSub'),
    url('markAttendance/', views.markAttendance, name='markAttendance'),
    url('editSub', views.editSub, name='editSub'),
    url('deleteSub', views.deleteSub, name='deleteSub'),
    path('expense/', views.expense, name='expense'),
    url('addLog', views.addEntry, name='addLog'),
    url('editLog', views.editEntry, name='editLog'),
    url('deleteLog', views.deleteEntry, name='deleteLog'),
    path('grade/', views.grade, name='grade'),
    url('addGrade/', views.addGrade, name='addGrade'),
    url('editGrade/', views.editGrade, name='editGrade'),
    url('deleteGrade', views.deleteGrade, name='deleteGrade'),
    path('reminders/', views.reminders, name='reminders'),
    url('addReminder/', views.addReminder, name='addReminder'),
    url('editReminder/', views.editReminder, name='editReminder'),
    url('deleteReminder', views.deleteReminder, name='deleteReminder'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SelfFolio/SelF/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime
from django.utils import timezone
import os

class Profile (models.Model):
    PROFILE_CATEGORY = (
        ('Student','Student'),
        ('Professional','Professional'),
    )

    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    Bio = models.TextField(blank = True, null=True)
    University = models.CharField(max_length = 50, null=True, blank=True)
    Profession = models.CharField(max_length=32, default='Student', choices=PROFILE_CATEGORY, null=True)
    DOB = models.DateField(null=True)
    profile_pic = models.ImageField(default="profile.png", null=True, blank=True)
    

    def __str__ (self):
        return self.user.username


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()



class Attendance(models.Model):
    subject = models.CharField(max_length = 50)
    code = models.CharField(max_length=32)
    present = models.IntegerField()
    absent = models.IntegerField()
    attendance = models.FloatField(null=True)
    userProfile = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__ (self):
        return self.code

class Expense(models.Model):
    EXPENSE_CATEGORY = (
        ('Health','Health'),
        ('Education','Education'),
        ('Food','Food'),
        ('Personal','Personal'),
    )
    price = models.PositiveIntegerField(null=True)
    item = models.CharField(max_length=100, null=True)
    date = models.DateField(null=True)
    category = models.CharField(max_length=50, choices=EXPENSE_CATEGORY, null=True)
    quantity = models.PositiveIntegerField(null=True)
    total = models.PositiveIntegerField(null=True)
    userProfile = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__ (self):
        return self.item


class Grade(models.Model):
    SEM_CATEGORY = (
        ('Sem 1', 'Sem 1'),
        ('Sem 2', 'Sem 2'),
        ('Sem 3', 'Sem 3'),
        ('Sem 4', 'Sem 4'),
        ('Sem 5', 'Sem 5'),
        ('Sem 6', 'Sem 6'),
        ('Sem 7', 'Sem 7'),
        ('Sem 8', 'Sem 8'),
    )
    semester = models.CharField(max_length=30, choices=SEM_CATEGORY)
    subject = models.CharField(max_length=50)
    code = models.CharField(max_length=32)
    credits = models.FloatField(null=True)
    pointer = models.PositiveIntegerField(validators=[MaxValueValidator(10)])
    creditsEarned = models.FloatField(null=True)
    userProfile = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.subject

class Reminders(models.Model):
    subject = models.CharField(max_length=50, null=True)
    code = models.CharField(max_length=32, null=True)
    task = models.TextField(null=True)
    dateNtime = models.DateTimeField(null=True)
    #date = models.DateField(null=True)
    #time = models.TimeField(null=True)
    userProfile = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.task

SelfFolio/SelF/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *


# Create your views here.

def logout_func(request):
    logout(request)
    return redirect('login_page')

def signup(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if User.objects.filter(username=request.POST['username']).exists():
            messages.error(request, "The username you entered is already taken")
            return redirect('signup')
        if form.is_valid():
            form.save()
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.DOB = form.cleaned_data.get('DOB')
            user.profile.Bio = form.cleaned_data.get('Bio')
            user.profile.Profession = form.cleaned_data.get('Profession')
            user.profile.University = form.cleaned_data.get('University')
            user.save()
            username = form.cleaned_data['username']
            messages.success(request, 'Account was created for ' + username)
            return redirect("login_page")
        else:
            messages.error(request, "Invalid form entries.")
            return redirect('signup')

    else:
        return render(request, "registration/signup.html", {"form": form})

'''
def home(request):
    Username = request.Profile.UserName
    return render(request, 'home.html', {
        'Username': Username,
        'FirstName': content.FirstName,
        'LastName': content.LastName,
        'Email': content.UserEmail,
        'DOB': content.DOB,
        'Bio': content.Bio,
        'University': content.University,
        'Profession': content.Profession,
    })
'''

@login_required(login_url='login_page')
def home(request):
    return render(request, 'home.html')

@login_required(login_url='login_page')
def profile(request):
    return render(request,'profile.html')

@login_required(login_url='login_page')
def editProfile(request):
    user_id = request.user.id
    user = User.objects.filter(id=user_id)
    form = UpdateUserForm(initial={
        'first_name': user[0].first_name,
        'last_name': user[0].last_name,
        'Bio': user[0].profile.Bio,
        'DOB': user[0].profile.DOB,
        'University': user[0].profile.University,
        'Profession': user[0].profile.Profession,
        'profile_pic': user[0].profile.profile_pic,
    })
    if request.method == 'GET':
        return render(request, 'editProfile.html', {
            'form': form
        })
    else:
        form = UpdateUserForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            Bio = form.cleaned_data.get('Bio')
            DOB = form.cleaned_data.get('DOB')
            University = form.cleaned_data.get('University')
            Profession = form.cleaned_data.get('Profession')
            profile_pic = form.cleaned_data.get('profile_pic')
            user.first_name = first_name
            user.last_name = last_name
            user.profile.Bio = Bio
            user.profile.DOB = DOB
            user.profile.University = University
            user.profile.Profession = Profession
            user.profile.profile_pic = profile_pic
            user.save()
            return redirect('profile')
        else:
            messages.error(request, "Invalid form entries.")
            return redirect('editProfile')

'''
def login_func(request):
    if request.method == 'GET':
        return render(request, 'registration/login.html')
    elif request.method == 'POST':
        user_name = request.POST['user_name']
        user_password = request.POST['user_password']
        if Profile.objects.filter(UserName=request.POST['user_name']).exists():
            if Profile.objects.get(UserName=request.POST['user_name']).Password == request.POST['user_password']:
                content = Profile.objects.get(UserName=user_name)
                #return redirect('home')
                return render(request, 'home.html', {
                    'Username': content.UserName,
                    'FirstName': content.FirstName,
                    'LastName': content.LastName,
                    'Email': content.UserEmail,
                    'DOB': content.DOB,
                    'Bio': content.Bio,
                    'University': content.University,
                    'Profession': content.Profession,
                })
            else:
                messages.error(request, "The email or password you entered is incorrect!")
                return render(request, 'registration/login.html')
        else:
            messages.error(request, "The email or password you entered is incorrect!")
            return render(request, 'registration/login.html')
'''

def login_func(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username or password is incorrect')

    return render(request, 'registration/login.html')

'''
@login_required(login_url='login_page')
def attendance(request):
    if request.method == 'GET':
        labels = []
        data = []

        queryset = Attendance.objects.order_by('-present').distinct()
        for subject in queryset:
            labels.append(subject.code)
            total=subject.present + subject.absent
            percent=subject.present/total
            data.append(percent)

        return render(request, 'attendance.html', {
            'labels': labels,
            'data': data,
        })

    else:
        sub = request.POST['subject']
        c = request.POST['code']
        present = request.POST['present']
        absent = request.POST['absent']
        attendance_info = Attendance.objects.create(
            subject = sub,
            code = c,
            present = present,
            absent =absent,
        )
        attendance_info.save()

        labels = []
        data = []

        queryset = Attendance.objects.order_by('-present').distinct()
        for subject in queryset:
            labels.append(subject.code)
            total=(subject.present) + (subject.absent)
            percent=(subject.present)/total
            data.append(percent)

        return render(request, 'attendance.html', {
            'labels': labels,
            'data': data,
        })
'''

@login_required(login_url='login_page')
def attendance(request):
    if request.method == 'GET':
        user_id = request.user.id
        courses = Attendance.objects.filter(userProfile=user_id)
        return render(request, 'attendance.html', {
            'courses': courses,
        })

@login_required(login_url='login_page')
def addSub(request):
    form = addSubject()
    if request.method == 'GET':
        return render(request, 'addSub.html', {
            'form': form
        })
    else:
        form = addSubject(request.POST)
        if form.is_valid():
            user_id = request.user.id
            user = User.objects.filter(id=user_id)
            subject = form.cleaned_data.get('subject')
            code = form.cleaned_data.get('code')
            new_subject = Attendance.objects.create(
                userProfile= user[0],
                code= code,
                subject= subject,
                present= 0,
                absent= 0,
                attendance= 0.0,
            )
            new_subject.save()
            return redirect('attendance')
        else:
            messages.error(request, "Invalid form entries.")
            return redirect('addSub')

@login_required(login_url='login_page')
def markAttendance(request):
    if request.method=='GET':
        return render(request, 'markAttendance.html')
    else:
        course_id=request.GET.get('id')
        status = request.POST['attendance']
        course = Attendance.objects.filter(id=course_id)
        present = course[0].present
        absent = course[0].absent
        if status == 'present':
            present += 1
            Attendance.objects.filter(id=course_id).update(present=present)
        else:
            absent += 1
            Attendance.objects.filter(id=course_id).update(absent=absent)
        total = present+absent
        attendance = present/total * 100
        Attendance.objects.filter(id=course_id).update(attendance=attendance)
        return redirect('attendance')

@login_required(login_url='login_page')
def editSub(request):
    subject_id = request.GET.get('id')
    course = Attendance.objects.filter(id=subject_id)
    form = addSubject(initial={
        'code': course[0].code,
        'subject': course[0].subject,
    })
    if request.method == 'GET':
        return render(request, 'addSub.html', {
            'form': form
        })
    else:
        form = addSubject(request.POST)
        if form.is_valid():
            user_id = request.user.id
            user = User.objects.filter(id=user_id)
            code = form.cleaned_data.get('code')
            subject = form.cleaned_data.get('subject')
            updated_course = course.update(
                userProfile=user[0],
                code=code,
                subject=subject,
            )
            return redirect('attendance')
        else:
            messages.error(request, "Invalid form entries.")

SelfFolio/SelF/templates/addLog.html
{% extends 'base.html' %}

{% block content %}

<br> <br> <br>

{% if messages %}
    {% for message in messages %}
        <h6 id="message">{{ message }}</h6>
    {% endfor %}
{% endif %}

<form method="POST">
        {% csrf_token %}
        <p>
        {{form.date.label}}
        {{form.date}}
        </p>

        <p>
        {{form.category.label}}
        {{form.category}}
        </p>

        <p>
        {{form.item.label}}
        {{form.item}}
        </p>

        <p>
        {{form.price.label}}
        {{form.price}}
        </p>

        <p>
        {{form.quantity.label}}
        {{form.quantity}}
        </p>

        <button type="submit">Submit</button>

    <a href="{% url 'expense' %}"> Back </a>

</form>

    <p>
    {{form.errors}}
    </p>



{% endblock %}

SelfFolio/SelF/templates/addReminder.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<script src="{% url 'js-catlog' %}"></script>
<script src="{% static 'admin/js/core.js' %}"></script>
<link rel="stylesheet" href="{% static 'admin/css/base.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/widgets.css' %}">

<br> <br> <br>

{% if messages %}
    {% for message in messages %}
        <h6 id="message">{{ message }}</h6>
    {% endfor %}
{% endif %}

<br><br>

<form method="POST">
        {% csrf_token %}

        <p>
        {{form.code.label}}
        {{form.code}}
        </p>

        <p>
        {{form.subject.label}}
        {{form.subject}}
        </p>

        <p>
        {{form.task.label}}
        {{form.task}}
        </p>

        <!--<div>
            <label for="dateNtime">Date and Time</label>
            <input type="datetime-local" id="dateNtime" name="dateNtime" required>
        </div> -->


        <!--<div class="input-group date" id="datetimepicker1" data-target-input="nearest">
            <label for="datetimepicker1">Date and Time</label>
            {{ form.dateNtime }}
            <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
            </div>
        </div>-->
    <p>
        <div>
        Date
        {{ form.date }}
        </div>
        <div>
        Time
        {{ form.time }}
        </div>
    </p>



        <button type="submit">Submit</button>

    <a href="{% url 'reminders' %}"> Back </a>

</form>

    <p>
    {{form.errors}}
    </p>

<!--<script>

  $(function () {
    $("#datetimepicker1").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
  });

</script>-->

<!--<script>
    $(function () {
    $("#id_dateNtime").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });
</script>-->


{% endblock %}

SelfFolio/SelF/templates/attendance.html
{% extends 'base.html' %}

{% load get_id %}

{% block content %}

<br> <br> <br>
<h4>Attendance</h4>
<br>
{% if courses %}
<table class="table" id="table">
    <thead class="thead-light">
        <tr>
            <th>Subject Code</th>
            <th>Subject Name</th>
            <th>Present</th>
            <th>Absent</th>
            <th>Attendance</th>
            <th>Mark Attendance</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
            <tr>
                <td>{{ course.code }}</td>
                <td>{{ course.subject }}</td>
                <td>{{ course.present }}</td>
                <td>{{ course.absent }}</td>
                <td>{{ course.attendance|floatformat:2 }} %</td>
                <td>
                    <a href="markAttendance/?id={{ course | get_id }}">Mark attendance</a>
                </td>
                <td><a href="editSub/?id={{ course.id }}">Edit</a></td>
                <td><a href="deleteSub/?id={{ course.id }}">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}

<a href="addSub">Add a course</a>


<!-- <form class="form-inline" method="POST" action="">
  {% csrf_token %}
  <div class="form-group">
    <label for="subject" class="control-label col-sm-1">Subject: </label>
    <div class="col-sm-3">
      <input id="subject" name="subject" type="char" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label for="code" class="control-label col-sm-1">Code: </label>
    <div class="col-sm-3">
      <input id="code" name="code" type="char" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label for="present" class="control-label col-sm-1">Present: </label>
    <div class="col-sm-2">
        <input id="present" name="present" type="number" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label for="absent" class="control-label col-sm-1">Absent: </label>
    <div class="col-sm-4">
      <input id="absent" name="absent" type="number" class="form-control">
    </div>
  </div>

  <div class="form-group">
  <button type="submit">
    Submit
  </button>
  </div>
  
</form>

<div id="container" style="width: 75%;">
<canvas id="bar-chart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>

var config = {
    type: 'horizontalBar',
    data: {
    datasets: [{
        data: {{ data|safe }},
        label: 'Attendance'
    }],
    labels: {{ labels|safe }}
    },
    options: {
    responsive: true
    }
};

window.onload = function() {
    var ctx = document.getElementById('bar-chart').getContext('2d');
    window.myattendence = new Chart(ctx, config);
};

</script> -->
  
{% endblock %}

SelfFolio/SelF/templates/deleteGrade.html
{% extends 'base.html' %}

{% block content %}

<br><br><br>
<p>Are you sure you want to delete {{ grade.subject }}</p>
<br>
<a href="{% url 'grade' %}">No, go back.</a>
<br> <br>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Yes</button>
</form>

{% endblock %}

SelfFolio/SelF/templates/deleteLog.html
{% extends 'base.html' %}

{% block content %}

<br><br><br>
<p>Are you sure you want to delete {{ expense.item }}</p>
<br>
<a href="{% url 'expense' %}">No, go back.</a>
<br> <br>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Yes</button>
</form>

{% endblock %}

SelfFolio/SelF/templates/deleteReminder.html
{% extends 'base.html' %}

{% block content %}

<br><br><br>
<p>Are you sure you want to delete {{ reminder.task }}</p>
<br>
<a href="{% url 'reminders' %}">No, go back.</a>
<br> <br>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Yes</button>
</form>

{% endblock %}

SelfFolio/SelF/templates/deleteSub.html
{% extends 'base.html' %}

{% block content %}

<br><br><br>
<p>Are you sure you want to delete {{ course.subject }}</p>
<br>
<a href="{% url 'attendance' %}">No, go back.</a>
<br> <br>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Yes</button>
</form>

{% endblock %}

SelfFolio/SelF/templates/expense.html
{% extends 'base.html' %}


{% block content %}

<br>

<h2>All my expenses</h2>
<br> <br>
<h6>Total expense = {{ complete_total }}</h6>

<div id="container" style="width: 75%;">
    <canvas id="pie-chart"></canvas>
    <br>
    <br>
    <center>
        <button type="button" class="btn btn-dark" > <a style="color: white" href="addLog">Log an expense</a> </button>
    </center>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)'
          ],
          label: 'Expense'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>



<!-- {% if entries %}
<h4>Total expenses</h4>
<br>
<table class="table" id="table">
    <thead class="thead-light">
        <tr>
            <th>User ID</th>
            <th>Date</th>
            <th>Category</th>
            <th>Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in entries %}
            <tr>
                <td>{{ request.user.id }}</td>
                <td>{{ entry.date }}</td>
                <td>{{ entry.category }}</td>
                <td>{{ entry.item }}</td>
                <td>{{ entry.price }}</td>
                <td>{{ entry.quantity }}</td>
                <td>{{ entry.total }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Total</td>
            <td>{{ complete_total }}</td>
        </tr>
    </tbody>
</table>
{% endif %} -->


<br> <br> <br>
{% if healthLogs %}
<h4>Expenditure in healthcare</h4>
<br>
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Date</th>
            <th>Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in healthLogs %}
            <tr>
                <td>{{ entry.date }}</td>
                <td>{{ entry.item }}</td>
                <td>{{ entry.price }}</td>
                <td>{{ entry.quantity }}</td>
                <td>{{ entry.total }}</td>
                <td><a href="editLog/?id={{ entry.id }}">Edit</a></td>
                <td><a href="deleteLog/?id={{ entry.id }}">Delete</a></td>
            </tr>
        {% endfor %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>Total</td>
            <td>{{ total1 }}</td>
        </tr>
    </tbody>
</table>
{% endif %}


<br> <br> <br>
{% if eduLogs %}
<h4>Expenditure in education</h4>
<br>
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Date</th>
            <th>Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in eduLogs %}
            <tr>
                <td>{{ entry.date }}</td>
                <td>{{ entry.item }}</td>
                <td>{{ entry.price }}</td>
                <td>{{ entry.quantity }}</td>
                <td>{{ entry.total }}</td>
                <td><a href="editLog/?id={{ entry.id }}">Edit</a></td>
                <td><a href="deleteLog/?id={{ entry.id }}">Delete</a></td>
            </tr>
        {% endfor %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>Total</td>
            <td>{{ total3 }}</td>
        </tr>
    </tbody>
</table>
{% endif %}


<br> <br> <br>
{% if foodLogs %}
<h4>Expenditure in food</h4>
<br>
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Date</th>
            <th>Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in foodLogs %}
            <tr>
                <td>{{ entry.date }}</td>
                <td>{{ entry.item }}</td>
                <td>{{ entry.price }}</td>
                <td>{{ entry.quantity }}</td>
                <td>{{ entry.total }}</td>
                <td><a href="editLog/?id={{ entry.id }}">Edit</a></td>
                <td><a href="deleteLog/?id={{ entry.id }}">Delete</a></td>
            </tr>
        {% endfor %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>Total</td>
            <td>{{ total2 }}</td>
        </tr>
    </tbody>
</table>
{% endif %}


<br> <br> <br>
{% if personalLogs %}
<h4>Expenditure in personal items</h4>
<br>
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Date</th>
            <th>Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in personalLogs %}
            <tr>
                <td>{{ entry.date }}</td>
                <td>{{ entry.item }}</td>
                <td>{{ entry.price }}</td>
                <td>{{ entry.quantity }}</td>
                <td>{{ entry.total }}</td>
                <td><a href="editLog/?id={{ entry.id }}">Edit</a></td>
                <td><a href="deleteLog/?id={{ entry.id }}">Delete</a></td>
            </tr>
        {% endfor %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>Total</td>
            <td>{{ total4 }}</td>
        </tr>
    </tbody>
</table>
{% endif %}

<br> <br>


{% endblock %}